server:
  port: 8030

spring:
  application:
    name: zuul-api-gateway

zuul:
  routes:
    a:
      path: /a/**
      serviceId: service-a
    b:
      path: /b/**
      serviceId: service-b

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

